version: '3.8'

services:
  mysql-service:
    image: vacations-mysql
    build: ./Database
    container_name: vacations-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD:
      # MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: vacatoins
    # volume for db files
    volumes:
      - vacations:/var/lib/mysql
  # -----------------------------------------------------------------------------
  api-service:
    depends_on:
      - mysql-service
    image: vacations-api
    build: ./Backend
    container_name: vacations-api
    ports:
      - 4000:4000
    restart: unless-stopped
    # overriding backend .env variables
    environment:
      # service name is the name of the virtual machine
      MYSQL_HOST: mysql-service
      # MYSQL_USER: root
      MYSQL_PASSWORD: 
  # -----------------------------------------------------------------------------

  # react-service:
  #   depends_on:
  #     - api-service
  #   image: vacations-react
  #   build: ./Frontend
  #   container_name: vacations-react
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped

  # -----------------------------------------------------------------------------

  # listing all volumes we're using
volumes:
  vacations:
